apiVersion: v1
kind: Service
metadata:
  name: mall-chat-service
  namespace: default
  labels:
    app: mall-chat
spec:
  selector:
    app: mall-chat
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
  type: ClusterIP
